# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Awarica AB
email: info@awarica.com
description: >- # this means to ignore newlines until "baseurl:"
  Awarica AB is a software development company based in Stockholm, Sweden. We specialize in open source development, apps, for mobile and web and cloud services.
url: 'https://awarica.com' # the base hostname & protocol for your site
twitter_username: dfahlander
github_username: dfahlander
include: ['contact.md', '.well-known']
exclude: ['*.sh']
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
encoding: UTF-8
gfm_quirks: paragraph_end

# Build settings
markdown: kramdown
permalink: short-urls-jekyll
